[versions]
junitVersion = "6.0.3"
detektVersion = "1.23.8"
ktlintVersion = "14.0.1"

[libraries]
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitVersion" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitVersion" }
junit-platform-launcher = "org.junit.platform:junit-platform-launcher:6.0.3"
truth = "com.google.truth:truth:1.4.5"

[plugins]
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlintVersion" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detektVersion" }
